FROM alpine AS primerLinux
RUN mkdir 10A
RUN echo "Mi primer docker" > 10A/archivo.txt
RUN echo "console.log('Hola NodeJS de Docker')" > ejemplo.js
RUN apk update && apk add --no-cache git
RUN git clone -b main https://github.com/Zoditu/10A-UTT.git

FROM ubuntu:latest as base
RUN apt-get -y update; apt-get -y install curl
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash && \
    apt-get -qqy install nodejs
#COPY --from=primerLinux ejemplo.js .
#RUN mkdir pruebas
#COPY Mathematics.js /pruebas
#COPY sumas.test.js /pruebas
#RUN cd pruebas && npm init --yes
#RUN cd pruebas && npm install jest@latest
#RUN npx jest sumas
COPY --from=primerLinux /10A-UTT /10A-Repo
RUN cd /10A-Repo && npm install
RUN cd /10A-Repo && npx jest newStore
CMD /bin/bash
